import type { NextPage } from 'next'
import Head from 'next/head'
import Script from 'next/script'

import AboutUs from './components/about_us'
import Navbar from './components/navbar';
import Welcome from './components/welcome';
import OurTeam from './components/our_team';
import GetApp from './components/get_app';
import Footer from './components/footer';
import Feature from './components/feature';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />

        {/* Tailwind Element */}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tw-elements/dist/css/index.min.css" />

        {/* Google fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link href="https://fonts.googleapis.com/css2?family=Acme&display=swap"></link>
        <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Caveat&display=swap" rel="stylesheet"></link>
      </Head>
      <Script src="https://cdn.jsdelivr.net/npm/tw-elements/dist/js/index.min.js"></Script>
      <Navbar></Navbar>
      <Welcome></Welcome>
      <AboutUs></AboutUs>
      <Feature></Feature>
      <GetApp></GetApp>
      <OurTeam></OurTeam>
      <Footer></Footer>
    </>
  )
}

export default Home
